#!/bin/sh
# Copyright (c) 2014 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### BEGIN INIT INFO
# Provides:          chameleon-updater
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start chameleon-updater at boot time
# Description:       Auto-update chameleond by checking any new version in
#                    the Google Cloud Storage and installing it.
### END INIT INFO

UPDATER_NAME='chameleon-updater'
DAEMON_NAME='chameleond'
CONFIG_FILE="/etc/default/${DAEMON_NAME}"
. "${CONFIG_FILE}"

MIRROR_URL='http://commondatastorage.googleapis.com/chromeos-localmirror'
BUNDLE_PATH='distfiles/chameleon-bundle'
BUNDLE_URL="${MIRROR_URL}/${BUNDLE_PATH}"

do_start () {
    echo 'Checking Chameleon update...'
    pushd /tmp > /dev/null
    LATEST_BUNDLE=$(wget -qO - "${BUNDLE_URL}/LATEST")
    wget -q "${BUNDLE_URL}/${LATEST_BUNDLE}"

    BUNDLE_DIR=${LATEST_BUNDLE%%-r*}
    LATEST_VERSION=${LATEST_BUNDLE#*-}
    LATEST_VERSION=${LATEST_VERSION%%.tar.gz}
    if [[ ${LATEST_VERSION} > ${BUNDLE_VERSION} ]]; then
        echo "Update Chameleon daemon: ${BUNDLE_VERSION} -> ${LATEST_VERSION}"
        tar zxf ${LATEST_BUNDLE}
        cd ${BUNDLE_DIR}
        make install BUNDLE_VERSION=${LATEST_VERSION}
        popd > /dev/null
    else
        echo 'No new update.'
    fi
}

do_stop () {
    echo 'do nothing'
}

case "$1" in
    start|stop)
        do_${1}
        ;;

    restart)
        do_stop
        do_start
        ;;

    *)
        echo "Usage: /etc/init.d/${UPDATER_NAME} {start|stop|restart}"
        exit 1
        ;;
esac
exit 0
